# Generated by Django 6.0.1 on 2026-01-29 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('annee_academique', models.CharField(max_length=20)),
                ('membres', models.ManyToManyField(blank=True, related_name='groupes_academiques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publie'), ('EN_COURS', 'En cours'), ('FERME', 'Ferme')], default='BROUILLON', max_length=20)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_crees', to=settings.AUTH_USER_MODEL)),
                ('groupes_autorises', models.ManyToManyField(blank=True, related_name='examens', to='gestion.groupeacademique')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('ENSEIGNANT', 'Enseignant'), ('ADMIN', 'Admin')], max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url_depot_git', models.URLField(max_length=500)),
                ('hash_commit', models.CharField(max_length=100)),
                ('soumis_le', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_TEST', 'En test'), ('CORRIGE', 'Corrige'), ('ECHEC', 'Echec')], default='EN_ATTENTE', max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='gestion.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('corrige_le', models.DateTimeField(auto_now_add=True)),
                ('soumission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='gestion.soumission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='soumission',
            constraint=models.UniqueConstraint(fields=('examen', 'etudiant'), name='unique_soumission_par_etudiant'),
        ),
    ]
