# Generated by Django 6.0.1 on 2026-02-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_soumission_code_source_optional_git_fields'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examen',
            table='Examen',
        ),
        migrations.AlterModelTable(
            name='groupeacademique',
            table='GroupeAcademique',
        ),
        migrations.AlterModelTable(
            name='journalaudit',
            table='JournalAudit',
        ),
        migrations.AlterModelTable(
            name='profil',
            table='Profil',
        ),
        migrations.AlterModelTable(
            name='resultat',
            table='Resultat',
        ),
        migrations.AlterModelTable(
            name='soumission',
            table='Soumission',
        ),
    ]
